### ISSUE TITLE
Add support for custom perturbations

### ISSUE THREAD

**Issue by iterix** [fiddler-labs/fiddler-auditor#15]
Auditor offers some default perturbations out of the box. This can be quite limiting and does not cover all cases. We shoudl aim to provide an elegant way to let users define their own perturbations.

**Comment by askarmel** [comment]
Could be interesting to use translation capabilities to enable different paraphrasing approach or even model inference in a different language

**Comment by iterix** [comment]
Hi @askarmel 👋 Thank you for taking out time to participate here! 🙌 

I'd like to understand your comment a little more as we add more built-in perturbations and provide abstractions to define custom ones. 

Are you suggesting a perturbation function that take in the initial prompt in Source Language -->  Translates to another language --> And then translates back to original language? Is my understanding correct?

**Comment by askarmel** [comment]
Yes this is what I am suggesting. This is an usual data augmentation technique in NLP so worth to give a try maybe

**Comment by iterix** [comment]
Thats sounds great. We'll add it the roadmap. Thank you for the suggestion!
