### ISSUE TITLE
Auditor doesn't work with Azure OpenAI yet

### ISSUE THREAD

**Issue by tspthomas** [fiddler-labs/fiddler-auditor#20]
If one wants to replace OpenAI with AzureOpenAI, the current implementation doesn't work. I could notice that even if you replace the import with `from langchain.llms import AzureOpenAI` and set all the right parameters, the method `generate_similar_sentences()` is always calling OpenAI with the same parameters.

![image](https://github.com/fiddler-labs/fiddler-auditor/assets/4240244/d33dd908-779b-49a8-b5be-5dd7dad5935c)

A potential fix would be to check if the `openai.api_type="azure"` and include additional parameters before calling ChatCompletion. I may be able to propose a fix in the next few days, but I just wanted to give a heads-up in case someone else wants to try it as well 😃 

Thanks for working on this!

**Comment by iterix** [comment]
closing this thanks to @tspthomas and his PR #21
