### ISSUE TITLE
Error during installing package on macOS

### ISSUE THREAD

**Issue by pavlo-kartavkin** [fiddler-labs/fiddler-auditor#33]
Hi,

I've tried to install fiddler-auditor but I'm constantly facing an error

My environment:
macOS 12.4
Python 3.8.9
pip 23.2.1 (also tried 20.2.3)
It happens for v0.0.1 and 0.0.2

**Logs:**
pip3 install fiddler-auditor
Defaulting to user installation because normal site-packages is not writeable
Collecting fiddler-auditor
  Obtaining dependency information for fiddler-auditor from https://files.pythonhosted.org/packages/ae/c3/bfd459c6a44960f19a04eb095faa13c1deded373965ef5b77676cf005032/fiddler_auditor-0.0.2-py3-none-any.whl.metadata
  Downloading fiddler_auditor-0.0.2-py3-none-any.whl.metadata (5.2 kB)
Collecting checklist==0.0.11 (from fiddler-auditor)
  Downloading checklist-0.0.11.tar.gz (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [148 lines of output]
      running egg_info
      creating /private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info
      writing /private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/requires.txt
      writing top-level names to /private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/top_level.txt
      writing manifest file '/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'CHANGES'
      warning: no files found matching 'requirements.txt'
      warning: no files found matching 'data' under directory '*'
      warning: no previously-included files matching '__pycache__' found under directory '*'
      warning: no previously-included files matching '*.pyc' found under directory '*'
      warning: no previously-included files matching '*.pyo' found under directory '*'
      warning: no previously-included files matching '*.orig' found under directory '*'
      warning: no previously-included files matching 'node_modules' found under directory '*'
      warning: no previously-included files matching '_release_data' found under directory '*'
      warning: no previously-included files matching 'visual_interface' found under directory '*'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-pip-egg-info-90b_ikdp/checklist.egg-info/SOURCES.txt'
      Defaulting to user installation because normal site-packages is not writeable
      Requirement already satisfied: jupyter in /Users/admin/Library/Python/3.8/lib/python/site-packages (1.0.0)
      Requirement already satisfied: notebook in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (7.0.2)
      Requirement already satisfied: qtconsole in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (5.4.3)
      Requirement already satisfied: jupyter-console in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (6.6.3)
      Requirement already satisfied: nbconvert in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (7.7.4)
      Requirement already satisfied: ipykernel in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (6.25.1)
      Requirement already satisfied: ipywidgets in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter) (8.1.0)
      Requirement already satisfied: appnope in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (0.1.3)
      Requirement already satisfied: comm>=0.1.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (0.1.4)
      Requirement already satisfied: debugpy>=1.6.5 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (1.6.7.post1)
      Requirement already satisfied: ipython>=7.23.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (8.12.2)
      Requirement already satisfied: jupyter-client>=6.1.12 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (8.3.0)
      Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (5.3.1)
      Requirement already satisfied: matplotlib-inline>=0.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (0.1.6)
      Requirement already satisfied: nest-asyncio in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (1.5.7)
      Requirement already satisfied: packaging in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (23.1)
      Requirement already satisfied: psutil in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (5.9.5)
      Requirement already satisfied: pyzmq>=20 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (25.1.1)
      Requirement already satisfied: tornado>=6.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (6.3.3)
      Requirement already satisfied: traitlets>=5.4.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipykernel->jupyter) (5.9.0)
      Requirement already satisfied: widgetsnbextension~=4.0.7 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipywidgets->jupyter) (4.0.8)
      Requirement already satisfied: jupyterlab-widgets~=3.0.7 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipywidgets->jupyter) (3.0.8)
      Requirement already satisfied: prompt-toolkit>=3.0.30 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-console->jupyter) (3.0.39)
      Requirement already satisfied: pygments in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-console->jupyter) (2.16.1)
      Requirement already satisfied: beautifulsoup4 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (4.12.2)
      Requirement already satisfied: bleach!=5.0.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (6.0.0)
      Requirement already satisfied: defusedxml in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (0.7.1)
      Requirement already satisfied: importlib-metadata>=3.6 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (6.8.0)
      Requirement already satisfied: jinja2>=3.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (3.1.2)
      Requirement already satisfied: jupyterlab-pygments in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (0.2.2)
      Requirement already satisfied: markupsafe>=2.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (2.1.3)
      Requirement already satisfied: mistune<4,>=2.0.3 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (3.0.1)
      Requirement already satisfied: nbclient>=0.5.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (0.8.0)
      Requirement already satisfied: nbformat>=5.7 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (5.9.2)
      Requirement already satisfied: pandocfilters>=1.4.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (1.5.0)
      Requirement already satisfied: tinycss2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbconvert->jupyter) (1.2.1)
      Requirement already satisfied: importlib-resources>=5.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from notebook->jupyter) (6.0.1)
      Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from notebook->jupyter) (2.7.2)
      Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from notebook->jupyter) (2.24.0)
      Requirement already satisfied: jupyterlab<5,>=4.0.2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from notebook->jupyter) (4.0.5)
      Requirement already satisfied: notebook-shim<0.3,>=0.2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from notebook->jupyter) (0.2.3)
      Requirement already satisfied: ipython-genutils in /Users/admin/Library/Python/3.8/lib/python/site-packages (from qtconsole->jupyter) (0.2.0)
      Requirement already satisfied: qtpy>=2.0.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from qtconsole->jupyter) (2.3.1)
      Requirement already satisfied: six>=1.9.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from bleach!=5.0.0->nbconvert->jupyter) (1.15.0)
      Requirement already satisfied: webencodings in /Users/admin/Library/Python/3.8/lib/python/site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)
      Requirement already satisfied: zipp>=0.5 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from importlib-metadata>=3.6->nbconvert->jupyter) (3.16.2)
      Requirement already satisfied: backcall in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.2.0)
      Requirement already satisfied: decorator in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.1.1)
      Requirement already satisfied: jedi>=0.16 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.18.1)
      Requirement already satisfied: pickleshare in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.7.5)
      Requirement already satisfied: stack-data in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.2)
      Requirement already satisfied: typing-extensions in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.4.0)
      Requirement already satisfied: pexpect>4.3 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.8.0)
      Requirement already satisfied: python-dateutil>=2.8.2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.8.2)
      Requirement already satisfied: platformdirs>=2.5 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (2.5.2)
      Requirement already satisfied: anyio>=3.1.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (3.7.1)
      Requirement already satisfied: argon2-cffi in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (23.1.0)
      Requirement already satisfied: jupyter-events>=0.6.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.7.0)
      Requirement already satisfied: jupyter-server-terminals in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.4.4)
      Requirement already satisfied: overrides in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (7.4.0)
      Requirement already satisfied: prometheus-client in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.17.1)
      Requirement already satisfied: send2trash>=1.8.2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.2)
      Requirement already satisfied: terminado>=0.8.3 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.17.1)
      Requirement already satisfied: websocket-client in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.6.2)
      Requirement already satisfied: async-lru>=1.0.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter) (2.0.4)
      Requirement already satisfied: jupyter-lsp>=2.0.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter) (2.2.0)
      Requirement already satisfied: tomli in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter) (2.0.1)
      Requirement already satisfied: babel>=2.10 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.12.1)
      Requirement already satisfied: json5>=0.9.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.9.14)
      Requirement already satisfied: jsonschema>=4.17.3 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (4.19.0)
      Requirement already satisfied: requests>=2.28 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.31.0)
      Requirement already satisfied: fastjsonschema in /Users/admin/Library/Python/3.8/lib/python/site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.18.0)
      Requirement already satisfied: wcwidth in /Users/admin/Library/Python/3.8/lib/python/site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.2.6)
      Requirement already satisfied: soupsieve>1.2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from beautifulsoup4->nbconvert->jupyter) (2.4.1)
      Requirement already satisfied: idna>=2.8 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.4)
      Requirement already satisfied: sniffio>=1.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)
      Requirement already satisfied: exceptiongroup in /Users/admin/Library/Python/3.8/lib/python/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.1.3)
      Requirement already satisfied: pytz>=2015.7 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from babel>=2.10->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.3)
      Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
      Requirement already satisfied: attrs>=22.2.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (23.1.0)
      Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.7.1)
      Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (1.3.10)
      Requirement already satisfied: referencing>=0.28.4 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.30.2)
      Requirement already satisfied: rpds-py>=0.7.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (0.9.2)
      Requirement already satisfied: python-json-logger>=2.0.4 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.7)
      Requirement already satisfied: pyyaml>=5.3 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (6.0.1)
      Requirement already satisfied: rfc3339-validator in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.4)
      Requirement already satisfied: rfc3986-validator>=0.1.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.1)
      Requirement already satisfied: ptyprocess>=0.5 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
      Requirement already satisfied: charset-normalizer<4,>=2 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (3.2.0)
      Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.0.4)
      Requirement already satisfied: certifi>=2017.4.17 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2023.7.22)
      Requirement already satisfied: argon2-cffi-bindings in /Users/admin/Library/Python/3.8/lib/python/site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (21.2.0)
      Requirement already satisfied: executing>=1.2.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (1.2.0)
      Requirement already satisfied: asttokens>=2.1.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
      Requirement already satisfied: pure-eval in /Users/admin/Library/Python/3.8/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.2)
      Requirement already satisfied: fqdn in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (1.5.1)
      Requirement already satisfied: isoduration in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (20.11.0)
      Requirement already satisfied: jsonpointer>1.13 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (2.4)
      Requirement already satisfied: uri-template in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (1.3.0)
      Requirement already satisfied: webcolors>=1.11 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (1.13)
      Requirement already satisfied: cffi>=1.0.1 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.15.1)
      Requirement already satisfied: pycparser in /Users/admin/Library/Python/3.8/lib/python/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.21)
      Requirement already satisfied: arrow>=0.15.0 in /Users/admin/Library/Python/3.8/lib/python/site-packages (from isoduration->jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter) (1.2.3)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-install-yxjk732q/checklist_dbeeaa67812f4535bc95e9b0f11c40fe/setup.py", line 56, in <module>
          setup(name='checklist',
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/Users/admin/Library/Python/3.8/lib/python/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-install-yxjk732q/checklist_dbeeaa67812f4535bc95e9b0f11c40fe/setup.py", line 53, in run
          enable_visual_interface()
        File "/private/var/folders/vl/qv9421fx7591g540g97r4dn80000gn/T/pip-install-yxjk732q/checklist_dbeeaa67812f4535bc95e9b0f11c40fe/setup.py", line 14, in enable_visual_interface
          notebook.nbextensions.install_nbextension_python(
      AttributeError: module 'notebook' has no attribute 'nbextensions'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
_________________

Is it a known issue?

**Comment by iterix** [comment]
HI @pavlo-kartavkin Thanks for reporting this error and providing details. I'll look into it.

**Comment by iterix** [comment]
hi @pavlo-kartavkin I root-caused the issue to a dependency that Auditor relies on, Microsoft's checklist, that has a non-standard build process. https://github.com/marcotcr/checklist/issues/144

I have patched the upstream issue and published a new release to pypi. Can you please try with the latest release (0.0.3) and let me know if this unblocks you. Thanks!
